baseurl: "https://dermellor.github.io/vegane-familienkueche/"
disablePathToLower: true
languageCode: de-de
title: Vegane Familienkueche
theme: gochowdown
googleAnalytics: 
defaultcontentlanguage: de
paginate: 20
canonifyurls: true
pygmentsstyle: monokai
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
pygmentsOptions: "linenos=table"
permalinks:
  posts: /posts/:year/:month/:title
params:
  author: Talitha Mellor
  description: Vegane Rezepte für die ganze Familie
  keywords: 'recipes'
  favicon_32: /images/favicon-32x32.png
  favicon_16: /images/favicon-16x16.png
  footercontent: 
  hidecredits: false
  hidecopyright: false
  showNavTitle: false            # Boolean: show site title in nav bar
menu:
  main:
    - name: Home
      weight: 1
      url: /
    - name: Category
      weight: 2
      url: /category/
    - name: Cuisine
      weight: 3
      url: /cuisine/
    - name: Tags
      weight: 4
      url: /tags/
taxonomies:
  category: category
  cusine: cuisine
  tag: tags
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true