baseurl: "https://dermellor.github.io/vegane-familienkueche/"
disablePathToLower: true
languageCode: de-de
title: Vegane Familienkueche
theme: gochowdown
googleAnalytics: 
defaultcontentlanguage: de
paginate: 20
canonifyurls: true
pygmentsstyle: monokai
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
pygmentsOptions: "linenos=table"
permalinks:
  posts: /posts/:year/:month/:title
params:
  author: Talitha Mellor
  description: Vegane Rezepte für die ganze Familie
  keywords: 'rezepte, vegan'
  favicon_32: /images/favicon-32x32.png
  favicon_16: /images/favicon-16x16.png
  footercontent: 
  hidecredits: true
  hidecopyright: true
  showNavTitle: true            # Boolean: show site title in nav bar
menu:
  main:
    - name: Home
      weight: 1
      url: /
    - name: Kategorien
      weight: 2
      url: /category/
taxonomies:
  categories: category
  cusine: cuisine
  tag: tags